### ISSUE TITLE
文件名中文乱码

### ISSUE THREAD

**Issue by zhangjinling** [ychongsaytc/deepwiki#2]
文件名中文乱码怎么解决？可以实现在线编辑吗？如果没有 有其他方式可以替代吗？谢谢！

**Comment by ychongsaytc** [comment]
@zhangjinling

可以使用 JSON 格式的目录代替，文件位置：
`index.json` 文件位于 DOCS 文档目录下，example: https://github.com/ychongsaytc/deepwiki/blob/master/deepwiki-docs-example/index.json

用法及说明：
https://github.com/ychongsaytc/deepwiki/blob/master/deepwiki-docs-example/05.%20Writing%20Documents.markdown#define-all-documents-in-configuration
