### ISSUE TITLE
Enhancement: DeepWiki read/write MD files and upload assets.

### ISSUE THREAD

**Issue by spencerthayer** [ychongsaytc/deepwiki#8]
This application would be amazing if it could write MD files and upload assets. Is this something in the scope? Or should I fork it?

**Comment by LeiYangGH** [comment]
I also want this feature, especially editing pages online.

**Comment by ychongsaytc** [comment]
Thanks for your advice.

DeepWiki is built as a **extremely lightweight** Markdown wiki system, the recommended way to modify document files is Git auto deployment, (S)FTP and rsync.

If you are looking for a collaboration based document software, WordPress would be a good choice.

**Comment by spencerthayer** [comment]
Understood. DeepWiki will likely never be useful for a lightweight community. Regular wiki software would be better suited.
